import { Collection } from './models/collection.model';

export const data: Collection[] = [
  {
    type: 'Folder',
    name: 'Folder 1',
    children: [
      {
        type: 'Folder',
        name: 'Folder 1.1',
        children: [
          {
            type: 'Folder',
            name: 'Folder 1.1.1',
            children: [
              {
                type: 'Folder',
                name: 'Folder 1.1.1.1',
                children: [],
                canAddChild: true,
                showOptions: false,
                selectionType: null,
                minimizeChildren: false,
                folderCount: 0,
                fileCount: 0,
              },
            ],
            canAddChild: true,
            showOptions: false,
            selectionType: null,
            minimizeChildren: false,
            folderCount: 1,
            fileCount: 0,
          },
          {
            type: 'Folder',
            name: 'Folder 1.2',
            children: [],
            canAddChild: true,
            showOptions: false,
            selectionType: null,
            minimizeChildren: false,
            folderCount: 0,
            fileCount: 0,
          },
        ],
        canAddChild: true,
        showOptions: false,
        selectionType: null,
        minimizeChildren: false,
        folderCount: 2,
        fileCount: 0,
      },
      {
        type: 'File',
        name: 'File 1.2',
        canAddChild: true,
        showOptions: false,
        selectionType: null,
      },
    ],
    canAddChild: true,
    showOptions: false,
    selectionType: null,
    minimizeChildren: false,
    folderCount: 1,
    fileCount: 1,
  },
  {
    type: 'Folder',
    name: 'Folder 2',
    children: [
      {
        type: 'Folder',
        name: 'Folder 2.1',
        children: [],
        canAddChild: true,
        showOptions: false,
        selectionType: null,
        minimizeChildren: false,
        folderCount: 0,
        fileCount: 0,
      },
      {
        type: 'File',
        name: 'File 2.1',
      },
    ],
    canAddChild: true,
    showOptions: false,
    selectionType: null,
    minimizeChildren: false,
    folderCount: 1,
    fileCount: 1,
  },
];
